# Awsaj power standards, verbatim codes + short labels from "Math Standards for Report Cards"
POWER = {
"K":[("K.CC.A.1","Counting and Cardinality","Count to 100 by ones and by tens"),
("K.CC.B.4","Counting and Cardinality","Relate numbers to quantities; connect counting to cardinality"),
("K.CC.B.6","Counting and Cardinality","Count to answer 'how many?' up to 20 / count out that many objects"),
("K.CC.C.7","Counting and Cardinality","Compare groups up to 10 as greater / less / equal"),
("K.OA.A.5","Operations and Algebraic Thinking","Add and subtract within 5"),
("K.NBT.A.1","Number and Operations in Base Ten","Compose and decompose 11 to 19 as ten ones and some ones"),
("K.MD.A.1","Measurement and Data","Describe measurable attributes of objects"),
("K.G.A.1","Geometry","Name shapes and describe relative positions")],
"G1":[("1.OA.A.1","Operations and Algebraic Thinking","Add and subtract within 20 to solve word problems"),
("1.OA.C.6","Operations and Algebraic Thinking","Add and subtract within 20, fluent within 10"),
("1.NBT.B.3","Number and Operations in Base Ten","Compare two two-digit numbers using >, =, <"),
("1.NBT.C.4","Number and Operations in Base Ten","Add within 100 using place value"),
("1.NBT.C.5","Number and Operations in Base Ten","Mentally find 10 more or 10 less"),
("1.MD.A.1","Measurement and Data","Order three objects by length; compare indirectly"),
("1.MD.A.2","Measurement and Data","Express length as a whole number of length units"),
("1.MD.B.3","Measurement and Data","Tell and write time in hours and half-hours"),
("1.G.A.1","Geometry","Defining vs non-defining attributes; build and draw shapes"),
("1.G.A.2","Geometry","Compose 2-D and 3-D shapes into composite shapes"),
("1.G.A.3","Geometry","Partition circles and rectangles into halves and fourths")],
"G2":[("2.OA.A.1","Operations and Algebraic Thinking","Add and subtract within 100 in one- and two-step word problems"),
("2.OA.B.2","Operations and Algebraic Thinking","Add and subtract within 20 fluently"),
("2.OA.C.3","Operations and Algebraic Thinking","Odd and even; equation as sum of two equal addends"),
("2.NBT.A.1","Number and Operations in Base Ten","Three-digit place value (hundreds, tens, ones)"),
("2.NBT.A.3","Number and Operations in Base Ten","Read and write numbers to 1000, incl. expanded form"),
("2.NBT.B.5","Number and Operations in Base Ten","Add and subtract within 100 fluently"),
("2.NBT.B.7","Number and Operations in Base Ten","Add and subtract within 1000 with models and place value"),
("2.MD.A.1","Measurement and Data","Measure length with rulers and other tools"),
("2.MD.B.5","Measurement and Data","Add and subtract within 100 to solve length word problems"),
("2.MD.B.6","Measurement and Data","Represent whole numbers and sums on a number line"),
("2.MD.C.8","Measurement and Data","Word problems with local currency and denominations"),
("2.G.A.1","Geometry","Recognise and draw shapes with specified attributes"),
("2.G.A.2","Geometry","Partition a rectangle into rows and columns of squares"),
("2.G.A.3","Geometry","Partition circles and rectangles into halves, thirds, fourths")],
"G3":[("3.OA.A.1","Operations and Algebraic Thinking","Interpret products of whole numbers (equal groups)"),
("3.OA.A.3","Operations and Algebraic Thinking","Multiply and divide within 100 to solve word problems"),
("3.OA.C.7","Operations and Algebraic Thinking","Multiply and divide within 100 fluently"),
("3.NF.A.1","Number and Operations - Fractions","Understand 1/b and a/b"),
("3.NF.A.2","Number and Operations - Fractions","Fractions as numbers on the number line"),
("3.NF.A.3","Number and Operations - Fractions","Equivalence and comparison of fractions"),
("3.NF.A.3.C","Number and Operations - Fractions","Whole numbers as fractions; fractions equivalent to whole numbers"),
("3.MD.A.1","Measurement and Data","Tell time to the nearest minute; time interval problems"),
("3.MD.B.3","Measurement and Data","Scaled picture and bar graphs; one- and two-step problems"),
("3.MD.B.4","Measurement and Data","Measure to halves and fourths of an inch; line plots"),
("3.MD.C.5","Measurement and Data","Understand area as an attribute of plane figures"),
("3.NBT.A.1","Number and Operations in Base Ten","Round whole numbers to the nearest 10 or 100"),
("3.G.A.1","Geometry","Shared attributes; quadrilateral categories"),
("3.G.A.2","Geometry","Partition shapes into parts with equal areas")],
"G4":[("4.OA.A.1","Operations and Algebraic Thinking","Multiplication equations as multiplicative comparison"),
("4.OA.A.3","Operations and Algebraic Thinking","Multi-step word problems; interpret remainders; estimate"),
("4.NBT.A.1","Number and Operations in Base Ten","A digit represents ten times the place to its right"),
("4.NBT.A.2","Number and Operations in Base Ten","Read, write and compare multi-digit whole numbers"),
("4.NBT.A.3","Number and Operations in Base Ten","Round multi-digit whole numbers to any place"),
("4.NBT.B.4","Number and Operations in Base Ten","Add and subtract multi-digit whole numbers"),
("4.NBT.B.5","Number and Operations in Base Ten","Multiply up to 4-digit by 1-digit and 2-digit by 2-digit"),
("4.NF.A.1","Number and Operations - Fractions","Equivalent fractions using visual models"),
("4.NF.A.2","Number and Operations - Fractions","Compare fractions with unlike numerators and denominators"),
("4.NF.B.3","Number and Operations - Fractions","a/b as a sum of 1/b; add and subtract fractions"),
("4.MD.A.1","Measurement and Data","Relative sizes of measurement units; conversion tables"),
("4.MD.A.2","Measurement and Data","Four operations in measurement word problems"),
("4.MD.C.5","Measurement and Data","Angles as geometric figures; angle measurement concepts"),
("4.G.A.1","Geometry","Draw and identify points, lines, rays, angles, parallel/perpendicular"),
("4.G.A.2","Geometry","Classify 2-D figures; recognise right triangles")],
"G5":[("5.OA.A.1","Operations and Algebraic Thinking","Use and evaluate parentheses, brackets, braces"),
("5.OA.A.2","Operations and Algebraic Thinking","Write and interpret numerical expressions"),
("5.OA.B.3","Operations and Algebraic Thinking","Two numerical patterns; ordered pairs; graph them"),
("5.NBT.A.1","Number and Operations in Base Ten","Place value: 10 times / 1-tenth relationships"),
("5.NBT.A.2","Number and Operations in Base Ten","Patterns with powers of 10; decimal point movement"),
("5.NBT.A.3","Number and Operations in Base Ten","Read, write and compare decimals to thousandths"),
("5.NBT.B.5","Number and Operations in Base Ten","Multiply multi-digit whole numbers fluently"),
("5.NBT.B.6","Number and Operations in Base Ten","Divide with up to 4-digit dividends and 2-digit divisors"),
("5.NBT.B.7","Number and Operations in Base Ten","Add, subtract, multiply, divide decimals to hundredths"),
("5.NF.B.3","Number and Operations - Fractions","Fraction as division; division word problems"),
("5.NF.B.6","Number and Operations - Fractions","Real-world problems multiplying fractions and mixed numbers"),
("5.MD.A.1","Measurement and Data","Convert among standard units within a system"),
("5.MD.C.5","Measurement and Data","Relate volume to multiplication and addition"),
("5.G.A.1","Geometry","Define a coordinate system with perpendicular axes"),
("5.G.A.2","Geometry","Graph points in the first quadrant to solve problems"),
("5.G.B.4","Geometry","Classify two-dimensional figures in a hierarchy")],
}

# Comment-derived coverage, 2025-26, from the actual CLASS comment docs for all four
# quarters (Q1, Q2, Q3, Q4). Q2 is the Semester 1 report; Q4 is the Semester 2 report.
# "+T" entries were named only in the grade-level Guidelines TEMPLATE for that quarter,
# not in the class doc.
REPORTED = {
"K": {"Q1":["K.CC.A.1","K.CC.B.4","K.CC.B.6"],
      "Q2":["K.CC.A.1","K.CC.B.4","K.G.A.1"],
      "Q3":["K.MD.A.1","K.OA.A.5"],
      "Q4":["K.CC.A.1","K.CC.B.6","K.CC.C.7","K.NBT.A.1","K.OA.A.5"]},
"G1": {"Q1":["1.NBT.B.3","1.G.A.1","1.OA.C.6"],
       "Q2":["1.NBT.B.3","1.NBT.C.4","1.NBT.C.5","1.OA.C.6"],
       "Q3":["1.MD.A.1","1.MD.A.2","1.OA.A.1","1.OA.C.6"],
       "Q4":["1.NBT.C.4","1.OA.A.1","1.MD.A.1","1.MD.A.2","1.G.A.1","1.G.A.2"]},
"G2": {"Q1":["2.NBT.A.1","2.NBT.A.3","2.NBT.B.5"],
       "Q2":["2.NBT.A.1","2.NBT.A.3","2.NBT.B.5","2.NBT.B.7","2.OA.B.2","2.OA.A.1","2.MD.B.6"],
       "Q3":["2.G.A.1","2.MD.A.1","2.MD.B.6"],
       "Q4":["2.MD.C.8","2.G.A.1"]},
"G3": {"Q1":["3.G.A.1"],
       "Q2":["3.OA.A.1","3.OA.C.7","3.NBT.A.1","3.MD.B.3"],
       "Q3":["3.NF.A.1","3.NF.A.3","3.MD.A.1","3.G.A.1","3.NBT.A.1"],
       "Q4":["3.MD.A.1","3.G.A.1"]},
"G4": {"Q1":["4.NBT.A.1","4.NBT.A.2","4.NBT.A.3","4.NBT.B.4","4.NBT.B.5"],
       "Q2":["4.NBT.A.1","4.NBT.A.2","4.NF.A.1"],
       "Q3":["4.NF.A.1","4.NF.A.2","4.MD.A.1","4.MD.A.2"],
       "Q4":["4.MD.C.5","4.G.A.1","4.G.A.2"]},
"G5": {"Q1":["5.NBT.A.1","5.NBT.A.3"],
       "Q2":["5.OA.B.3","5.G.A.1","5.G.A.2","5.NBT.B.5","5.G.B.4","5.NBT.B.6","5.OA.A.1","5.OA.A.2"],
       "Q3":["5.OA.A.1","5.OA.A.2","5.NBT.B.5","5.NBT.B.6"],
       "Q4":["5.NF.B.3","5.OA.A.1"]},
}
# power standards named ONLY by the quarter template, never by a class doc
TEMPLATE_ONLY = {("G5","Q2"):["5.G.B.4","5.NBT.B.6","5.OA.A.1","5.OA.A.2"]}
GRADE_LABEL={"K":"Kindergarten (WRM Year 1)","G1":"Grade 1 (WRM Year 2)","G2":"Grade 2 (WRM Year 3)",
"G3":"Grade 3 (WRM Year 4)","G4":"Grade 4 (WRM Year 5)","G5":"Grade 5 (WRM Year 6)"}
